//POST SCHOOL REGISTRATION REQUEST
POST http://localhost:5000/api/admin/school-reg-request
Content-Type: application/json

{
    "name":"ABC high schhol",
    "address":"123 Drive Avenue Saudi Arabia",
    "email":"EFGH@school.com",
    "phone":"1234567890",
    "regNo":"1243GB12",
    "contactPerson":"John Doe"
}
###
//Get SCHOOL by ID
GET http://localhost:5000/api/admin/school-reg-request/6425c21a8550df2bd0f976bf

###
//Get all SCHOOLS
GET http://localhost:5000/api/admin/school-reg-request
###
//Admin updates school status with "approved"
PATCH  http://localhost:5000/api/admin/school-reg-request/6425c21a8550df2bd0f976bf
Content-Type: application/json

{
   "status":"approved"
}
###
//Create Academic Year
POST http://localhost:5000/api/schools/academic-year
Content-Type: application/json

{
    "title":"2023 winter session",
    "year":"2023"
   
}
###
//get all Academic Year
GET http://localhost:5000/api/schools/academic-year
Content-Type: application/json

###
//Create Academic class
POST http://localhost:5000/api/schools/academic-class
Content-Type: application/json

{
    "name":"Level 1",
    "academicYear":"6432fd66788343ae3b08e17c"
   
}
###
//Update Academic class
PATCH http://localhost:5000/api/schools/academic-class/643301942a2f70ce9307953c
Content-Type: application/json

{
    "name":"Level 1 updated",
    "academicYear":"6432fd66788343ae3b08e17c"
   
}
###
//get all Academic Class
GET http://localhost:5000/api/schools/academic-class

###
//Delete Academic class
DELETE http://localhost:5000/api/schools/academic-class/6432ff3c3e3d8e56c72eb0ed
###
//Generate public and private api keys
POST http://localhost:5000/api/api-keys/
Content-Type: application/json

{
    "name":"John Doe"
}


