//POST SCHOOL REGISTRATION REQUEST
POST http://localhost:5000/api/admin/school-reg-request
Content-Type: application/json

{
    "name":"ABC high schhol",
    "address":"123 Drive Avenue Saudi Arabia",
    "email":"EFGH@school.com",
    "phone":"1234567890",
    "regNo":"1243GB12",
    "contactPerson":"John Doe"
}
###
//Get SCHOOL by ID
GET http://localhost:5000/api/admin/school-reg-request/6425c21a8550df2bd0f976bf

###
//Get all SCHOOLS
GET http://localhost:5000/api/admin/school-reg-request
###s
//Admin updates school status with "approved"
PATCH  http://localhost:5000/api/admin/school-reg-request/6425c21a8550df2bd0f976bf
Content-Type: application/json

{
   "status":"approved"
}
